title: IS-403 Optical sensor for precision agriculture
description: IS-403 Report for Optical sensor for precision agriculture
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_enabled: true
heading_anchors: true
